### ISSUE TITLE
Turning off the split bar does not seem to actually work

### ISSUE THREAD

**Issue by rbreaves** [charlietag/tmux-split-statusbar#2]
On top of that removal of the plugin seems to be impossible. It has left my tmux installed in a split mode that I am unable to remove or toggle.

**Comment by rbreaves** [comment]
For whatever reason your toggle off function does not successfully run on my system. I have ran it manually though by running the commands in sequence. Once I ran this I could then remove the plugin from my .tmux.conf file. I hope you continue to work on improving this plugin as I love the concept and can see needing it in the near future, but for now I plan to leave it disabled. Maybe another plugin interferes with it, I don't use many, but I do use resurrect, continuum, thyme and thewtex/tmux-mem-cpu-load.

```
  tmux set -g status-format\[0\] `tmux show-option -gqv "status-format[6]"`
  tmux set -g status-format\[1\] `tmux show-option -gqv "status-format[7]"`
  tmux set -g status on
```

**Comment by charlietag** [comment]
Hi @rbreaves ,
Glad you are trying to use this plugin.

Maybe it is because default hot-key `F11` , `F12` is not working on your system.

Could you try to change it to `S` , `H` as the following:

1. vi **~/.tmux.conf**
`set -g @split-statusbar-bindkey 'S'`
`set -g @split-status-hide-bindkey 'H'`

2. Reload config
`tmux source-file ~/.tmux.conf `

3.  Try hide / Toggle status bar
`CTRL-A -> S`  or `CTRL-B -> S`
`CTRL-A -> H`  or `CTRL-B -> H`
